// Lightweight curated emoji set for the signup picker.
// Avoids the 1MB+ emoji-mart dependency. Each entry has a char + searchable keywords.

export interface EmojiEntry {
  c: string; // character
  k: string; // space-separated keywords (lowercase)
}

export const EMOJIS: EmojiEntry[] = [
  // Faces
  { c: "😀", k: "smile happy face grin" },
  { c: "😎", k: "cool sunglasses face" },
  { c: "🤓", k: "nerd geek face glasses" },
  { c: "🥷", k: "ninja stealth warrior" },
  { c: "🧙", k: "mage wizard magic" },
  { c: "🦸", k: "hero superhero cape" },
  { c: "🤖", k: "robot bot ai" },
  { c: "👽", k: "alien ufo space" },
  { c: "👻", k: "ghost spooky" },
  { c: "💀", k: "skull death bone" },
  { c: "🎃", k: "pumpkin halloween" },
  { c: "🤡", k: "clown joker" },
  { c: "🥶", k: "cold freeze ice face" },
  { c: "🔥", k: "fire flame hot lit" },
  { c: "✨", k: "sparkle shine magic" },
  { c: "⚡", k: "lightning bolt thunder fast" },
  { c: "💎", k: "diamond gem jewel" },
  { c: "👑", k: "crown king queen royal" },
  // Animals — Nepal & wild
  { c: "🐅", k: "tiger predator stripe" },
  { c: "🐆", k: "leopard snow cat wild" },
  { c: "🦁", k: "lion king pride" },
  { c: "🐺", k: "wolf pack howl" },
  { c: "🦊", k: "fox clever cunning" },
  { c: "🐻", k: "bear strength" },
  { c: "🦅", k: "eagle bird hawk fly" },
  { c: "🦉", k: "owl wise night bird" },
  { c: "🦇", k: "bat night fly" },
  { c: "🐉", k: "dragon mythical" },
  { c: "🦄", k: "unicorn mythical horn" },
  { c: "🐎", k: "horse mustang gallop" },
  { c: "🐂", k: "ox bull strong" },
  { c: "🐘", k: "elephant huge tusk" },
  { c: "🦏", k: "rhino horn" },
  { c: "🦬", k: "buffalo bison" },
  { c: "🐢", k: "turtle tortoise" },
  { c: "🐍", k: "snake serpent" },
  { c: "🦂", k: "scorpion sting" },
  { c: "🕷️", k: "spider web" },
  { c: "🦀", k: "crab claw" },
  { c: "🐙", k: "octopus tentacle" },
  { c: "🦈", k: "shark fin teeth" },
  { c: "🐳", k: "whale ocean" },
  { c: "🐬", k: "dolphin" },
  { c: "🐧", k: "penguin cold" },
  { c: "🦜", k: "parrot tropical bird" },
  { c: "🦚", k: "peacock feather" },
  // Nepal / culture
  { c: "🏔️", k: "mountain everest snow peak" },
  { c: "⛰️", k: "mountain hill" },
  { c: "🗻", k: "mount fuji peak" },
  { c: "🏞️", k: "national park valley" },
  { c: "🛕", k: "temple hindu pashupati" },
  { c: "☸️", k: "wheel dharma buddha lumbini" },
  { c: "🕉️", k: "om hindu sacred" },
  { c: "🪔", k: "diya lamp tihar deepawali" },
  { c: "🪷", k: "lotus flower buddha" },
  { c: "🌺", k: "flower hibiscus" },
  { c: "🥟", k: "momo dumpling" },
  { c: "🍛", k: "curry dal bhat rice" },
  { c: "🍵", k: "tea chiya cup" },
  // Weapons & gear
  { c: "⚔️", k: "swords battle khukuri war" },
  { c: "🗡️", k: "dagger khukuri blade" },
  { c: "🛡️", k: "shield defend protect" },
  { c: "🏹", k: "bow arrow archer" },
  { c: "🔫", k: "gun pistol" },
  { c: "💣", k: "bomb explosive" },
  { c: "🧨", k: "dynamite tnt" },
  { c: "🎯", k: "target dart bullseye" },
  // Nature & weather
  { c: "🌙", k: "moon night crescent" },
  { c: "☀️", k: "sun day" },
  { c: "⭐", k: "star" },
  { c: "🌟", k: "glowing star" },
  { c: "💫", k: "dizzy star sparkle" },
  { c: "🌈", k: "rainbow pride" },
  { c: "🌊", k: "wave ocean water" },
  { c: "❄️", k: "snowflake cold ice" },
  { c: "🌪️", k: "tornado wind cyclone" },
  { c: "🌋", k: "volcano lava" },
  { c: "🌍", k: "earth globe world" },
  { c: "🪐", k: "saturn planet space" },
  { c: "🌌", k: "milky way galaxy" },
  // Activity & sports
  { c: "🚣", k: "row boat raft pokhara" },
  { c: "🚵", k: "mountain bike cyclist" },
  { c: "🏃", k: "run runner sprint" },
  { c: "🧗", k: "climber climb rock" },
  { c: "⛷️", k: "ski snow" },
  { c: "🏂", k: "snowboard" },
  { c: "🪂", k: "paraglide skydive" },
  { c: "🎮", k: "controller game gamer" },
  { c: "🕹️", k: "joystick retro arcade" },
  { c: "🎲", k: "dice luck random" },
  { c: "🎰", k: "slot casino jackpot" },
  { c: "🏆", k: "trophy winner first" },
  { c: "🥇", k: "gold medal first" },
  { c: "🎖️", k: "medal honor military" },
  // Tech & symbols
  { c: "🛰️", k: "satellite gps space" },
  { c: "🚀", k: "rocket launch fast" },
  { c: "🛸", k: "ufo flying saucer" },
  { c: "📡", k: "antenna signal" },
  { c: "🔭", k: "telescope astronomy" },
  { c: "⚙️", k: "gear cog mechanic" },
  { c: "🧬", k: "dna science gene" },
  { c: "💻", k: "laptop computer dev" },
  { c: "🖥️", k: "desktop computer monitor" },
  { c: "📱", k: "phone mobile cell" },
  { c: "🎧", k: "headphone music audio" },
  { c: "🎸", k: "guitar music rock" },
  { c: "🎹", k: "piano music keys" },
  { c: "🥁", k: "drum music beat" },
  // Hearts & abstract
  { c: "❤️", k: "red heart love" },
  { c: "🧡", k: "orange heart" },
  { c: "💛", k: "yellow heart" },
  { c: "💚", k: "green heart" },
  { c: "💙", k: "blue heart" },
  { c: "💜", k: "purple heart" },
  { c: "🖤", k: "black heart" },
  { c: "🤍", k: "white heart" },
  { c: "💯", k: "100 perfect score" },
  { c: "🎴", k: "card flower play" },
  { c: "🃏", k: "joker card wild" },
  { c: "🧿", k: "evil eye nazar amulet" },
  { c: "🔱", k: "trident shiva" },
  { c: "⚜️", k: "fleur de lis royal" },
  { c: "🪬", k: "hamsa hand protection" },
];

export const DEFAULT_EMOJIS = ["🦅", "🏔️", "🐆", "🛕", "⚔️"];

export function searchEmoji(q: string, limit = 60): EmojiEntry[] {
  const term = q.trim().toLowerCase();
  if (!term) return EMOJIS.slice(0, limit);
  return EMOJIS.filter((e) => e.k.includes(term) || e.c === term).slice(0, limit);
}
